### PR TITLE
update hvcc and add dpf-widgets

### PR DESCRIPTION
**Pull request by dromer**

### CODE REVIEW

**Comment by dromer** [comment]
Still not sure to what extend we can start building UI with dpf-widgets, but at least we can start trying stuff (and code export works).

**Comment by dromer** [comment]
Needs a bit more testing before merge.

**Comment by dromer** [comment]
Heuhm, trying to update to latest hvcc release and somehow the pyinstaller build exploded o.O

The only dependency I added was pydantic, but that shouldn't add a whopping +100MB to the size ..

**Comment by dromer** [comment]
Looking at moving hvcc to `poetry` and using the `poetry-pyinstaller-plugin` this gives a result that's more like expected.
Will need a bit of work to integrate it with the toolchain though.

**Comment by dromer** [comment]
Test going on here: https://github.com/Wasted-Audio/hvcc/pull/199

Creates a single binary that does everything.
I also found the culprit for the `generators` needing an additional import.

**Comment by dromer** [comment]
Hmm, Windows builds fail due to number of files: https://github.com/Wasted-Audio/plugdata-heavy-toolchain/actions/runs/11065615856

`Error: EMFILE: too many open files, open 'D:\a\plugdata-heavy-toolchain\plugdata-heavy-toolchain\Heavy\usr\share\perl5\core_perl\Test\Tester\Capture.pm'`

**Comment by dromer** [comment]
So other than Windows archive upload this all should work.

Any suggestion on how to fix this? Recommendation is to first zip the target dir, but then we need another step to unpack it on the plugdata side.

**Comment by timothyschoen** [comment]
Looks like this is now fixed by Github: https://github.com/actions/upload-artifact/issues/485

**Comment by timothyschoen** [comment]
Nice though, upload-artifact@v4 should really speed it up

**Comment by timothyschoen** [comment]
Perhaps we could find a way to speed up the Windows build still... It spends half of the time downloading and extracting minGW

**Comment by dromer** [comment]
yeah it takes quite a long time!

**Pull request merged**
